# -*- python -*-
from lsst.sconsUtils import scripts, env
import os

pgpassfile = os.getenv("PGPASSFILE")
pguser = os.getenv("PGUSER")
if pgpassfile:
    env["ENV"]["PGPASSFILE"] = pgpassfile
if pguser:
    env["ENV"]["PGUSER"] = pguser

scripts.BasicSConscript.tests(pyList=[])
